name = "gemini-landing"
main = "dist/_worker.js"
compatibility_date = "2026-06-01"
workers_dev = true

[[routes]]
pattern = "no6.buildwithoracle.com/*"
zone_name = "buildwithoracle.com"

[[routes]]
pattern = "gemini.buildwithoracle.com/*"
zone_name = "buildwithoracle.com"

[assets]
directory = "./dist"


